using System.Text;
using System.Text.Json;
using Lilia.Core.Entities;

namespace Lilia.Api.Services;

/// <summary>
/// BibTeX <c>.bib</c> serialization shared by the LaTeX export ZIP
/// path and the Typst preview compile path. The two pipelines need
/// the same bib file alongside <c>main.tex</c> / <c>main.typ</c> for
/// citation rendering to resolve.
///
/// Field set is intentionally narrow — title/author/year/journal/
/// booktitle/volume/number/pages/publisher/doi/url. New fields land
/// here, not in callers.
/// </summary>
public static class BibTeXSerializer
{
    private static readonly string[] DefaultFields =
    {
        "author", "title", "year", "journal", "booktitle",
        "volume", "number", "pages", "publisher", "doi", "url",
    };

    public static string Serialize(IReadOnlyCollection<BibliographyEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("% Bibliography file generated by Lilia");
        sb.AppendLine($"% Generated on {DateTime.UtcNow:O}");
        sb.AppendLine();

        foreach (var entry in entries)
        {
            sb.AppendLine($"@{entry.EntryType ?? "article"}{{{entry.CiteKey},");

            var data = entry.Data?.RootElement;
            if (data.HasValue)
            {
                foreach (var field in DefaultFields)
                {
                    AppendField(sb, data.Value, field);
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void AppendField(StringBuilder sb, JsonElement data, string field)
    {
        if (data.TryGetProperty(field, out var val) && val.ValueKind == JsonValueKind.String)
        {
            var value = val.GetString();
            if (!string.IsNullOrEmpty(value))
                sb.AppendLine($"  {field} = {{{value}}},");
        }
    }
}
