-- =====================================================================
--  E2E scenario seed — covers the 7 current Playwright spec files.
--
--  Each scenario row also gets a version-1 `scenario_version`
--  (detail_level='l3', generation_provenance='imported') and the
--  scenario.current_version_id is set to that version.
--
--  Fingerprints (automation_content) were generated by
--  node -e "createHash('sha256').update(slug).digest('hex').slice(0,16)"
--  and match the slug -> fingerprint mapping that e2e/helpers/scenario.ts
--  computes at runtime.
--
--  Idempotent: ON CONFLICT(slug) DO NOTHING for scenarios; the version
--  row insert is guarded by NOT EXISTS to avoid duplicates on re-run.
-- =====================================================================

BEGIN;

WITH m AS (SELECT id, slug FROM e2e.module),
     s AS (SELECT id, module_id, slug FROM e2e.surface)
INSERT INTO e2e.scenario (
  slug, title, description, module_id, target_surface_id,
  criticality, detail_level, review_state, execution_mode,
  template, automation_content, milestone, created_by
)
SELECT v.slug,
       v.title,
       v.description,
       m.id,
       CASE WHEN v.surface_slug IS NULL THEN NULL
            ELSE (SELECT id FROM s WHERE module_id = m.id AND slug = v.surface_slug)
       END,
       v.criticality, 'l3', 'approved', 'integration',
       'standard', v.fingerprint, 'conversion-launch', 'oussama'
FROM (VALUES
  -- auth.spec.ts
  ('auth.session-jwt-minted',         'auth',  NULL,                       'Setup mints a non-empty Stytch session JWT (E2E project, valid iss/exp).',                 'Setup project minted a valid JWT on the E2E Stytch project.',   '7099233a411eb778', 'p0'),
  ('auth.cookies-loaded',             'auth',  NULL,                       'Stytch session cookies are loaded into the browser via storageState.',                       'storageState load was honoured by the browser.',                '5d91bf8603d44b41', 'p0'),
  ('auth.dashboard-route-resolves',   'auth',  'sign-in-page',             'Dashboard route resolves for the authenticated user (no redirect to /sign-in).',             '/latex/docs reachable without auth bounce.',                   '74de6cb14fe172a5', 'p0'),
  -- documents.spec.ts
  ('documents.crud-roundtrip',        'dashboard', 'doc-grid',             'API: create + read + delete round-trip on a document.',                                       'Document CRUD via /api/documents works end-to-end.',           'f5753af9b0152c20', 'p0'),
  ('documents.dashboard-renders-new-doc','dashboard','doc-grid',           'UI: dashboard shows a newly-created doc within ~30s of API creation.',                        'Dashboard React Query cache picks up new docs.',               '9c4edaa331496ddf', 'p1'),
  ('documents.studio-mounts-for-id',  'dashboard', 'doc-card',             'UI: studio page mounts for a known doc id (no UI click — direct nav).',                       'Replacement for the click-to-open scenario; new dashboard UX intercepts single-click.',  '118597dd693ad561', 'p1'),
  -- blocks.spec.ts
  ('blocks.create-all-canonical-types','studio','block-canvas',            'API: create blocks of every canonical type (13 types).',                                      'Validates the C# API accepts the full block_type catalogue.',  '07b0d21e81a7de2e', 'p0'),
  ('blocks.list-reflects-ordering',   'studio','block-canvas',             'API: list reflects sort_order across multiple blocks.',                                       'Block ordering round-trips via /blocks list.',                 'abba55443c0be982', 'p1'),
  ('blocks.studio-renders-multiple-blocks','studio','block-canvas',        'UI: studio renders multiple blocks (heading + paragraph) seeded via API.',                    'Editor mounts and renders seeded content.',                    'ea0d9cd0cf1ae1bb', 'p0'),
  -- save.spec.ts
  ('save.block-update-persists',      'studio','block-card',               'API: block content update persists across reads.',                                            'PUT /blocks/:id updates content.text correctly.',              '2a09e6adc9bf9270', 'p0'),
  ('save.document-title-persists',    'studio','topbar',                   'API: document title update persists.',                                                        'PUT /documents/:id renames the document.',                     '1a29f7d474c870b9', 'p1'),
  ('save.studio-renders-seeded-block','studio','block-canvas',             'UI: seeded paragraph block renders in the studio Cards view.',                                'Replacement for "edit-then-reload" — race-y due to RQ persist cache.', '974d1617288bbb2b', 'p1'),
  -- export.spec.ts
  ('export.latex-returns-non-empty',  'export','export-dialog',            'API: LaTeX export returns non-empty content for a document with 2 blocks.',                   'Conversion launch-critical: LaTeX path produces output.',      'c41203c734461237', 'p0'),
  ('export.markdown-returns-non-empty','export','export-dialog',           'API: Markdown export returns non-empty content.',                                             'Conversion launch-critical: Markdown path produces output.',   '209fb108dd5efc4f', 'p1'),
  ('export.html-returns-non-empty',   'export','export-dialog',            'API: HTML export returns non-empty content.',                                                 'Conversion launch-critical: HTML path produces output.',       'e2d666df273839d1', 'p1'),
  -- import.spec.ts
  ('import.docx-upload-returns-id',   'import','import-dialog',            'DOCX upload returns a job/session id via the conversion endpoint.',                           'Conversion launch-critical: DOCX intake works.',               'ce9348dd39926c63', 'p1'),
  ('import.review-sessions-reachable','import','import-review-page',       'GET /api/lilia/import-review/sessions returns a non-404 status (route exists).',             'Smoke check: review feature exposed.',                          '6ad1f0f6ad7eacd3', 'p2'),
  -- mobile.spec.ts
  ('mobile.dashboard-mounts',         'mobile','mobile-studio',            'Mobile viewport: dashboard renders document chrome on Pixel 7.',                              'Catches regressions in dashboard mobile shell.',                '8c2dd07cfa249bd1', 'p0'),
  ('mobile.studio-mounts-no-error',   'mobile','mobile-studio',            'Mobile studio mounts without "undefined is not an object (evaluating ..id)" errors.',         'Guards yesterday''s StudioMobile ShareDrawer fix (Sentry 7489011746).', 'f5a8231546ce58cb', 'p0'),
  ('mobile.chrome-elements-present',  'mobile','mobile-bottom-rail',       'Mobile studio shows the Document panels + Add buttons in the bottom rail.',                  'Asserts the post-launch mobile chrome elements ship.',         '263e829732002667', 'p1')
) AS v(slug, module_slug, surface_slug, title, description, fingerprint, criticality)
JOIN m ON m.slug = v.module_slug
ON CONFLICT (slug) DO UPDATE
  SET title = EXCLUDED.title,
      description = EXCLUDED.description,
      target_surface_id = EXCLUDED.target_surface_id,
      automation_content = EXCLUDED.automation_content,
      milestone = EXCLUDED.milestone,
      updated_at = NOW();

-- Insert version 1 (L3, imported) for every scenario that doesn't have one.
INSERT INTO e2e.scenario_version (
  scenario_id, version_number, detail_level, title, description,
  steps, generation_provenance, generated_by
)
SELECT
  sc.id, 1, 'l3', sc.title, sc.description,
  '[]'::jsonb, 'imported', 'oussama'
FROM e2e.scenario sc
WHERE NOT EXISTS (
  SELECT 1 FROM e2e.scenario_version v
  WHERE v.scenario_id = sc.id AND v.version_number = 1
);

-- Wire current_version_id to point at the newly-inserted version.
UPDATE e2e.scenario sc
SET current_version_id = v.id, updated_at = NOW()
FROM e2e.scenario_version v
WHERE v.scenario_id = sc.id
  AND v.version_number = 1
  AND sc.current_version_id IS DISTINCT FROM v.id;

-- Sanity output.
DO $$
DECLARE c INTEGER;
BEGIN
  SELECT COUNT(*) INTO c FROM e2e.scenario WHERE NOT is_deleted;
  RAISE NOTICE 'e2e scenarios seeded: % rows', c;
END
$$;

COMMIT;
