-- =====================================================================
--  Flow-editor scenario seed — L1 stubs for the continuous-prose
--  editor (/document/:id). 136 scenarios: 27 key flow
--  scenarios + 109 block-deep stubs (13 block types x flow
--  actions). Generated by scripts/e2e/generate-flow-scenarios.mjs.
--
--  Requires 029_seed_flow_catalogue.sql (the `flow` module +
--  surfaces) to have been applied first.
--
--  Idempotent: ON CONFLICT(slug) DO NOTHING for the scenario rows,
--  guarded NOT EXISTS for the version rows. Re-run safe.
--
--  Seeded scenarios start in review_state='draft', detail_level
--  'l1'. Promote to 'l2'/'l3' as Playwright tests are written.
-- =====================================================================

BEGIN;

WITH m AS (SELECT id, slug FROM e2e.module),
     s AS (SELECT id, module_id, slug FROM e2e.surface)
INSERT INTO e2e.scenario (
  slug, title, description, module_id, target_surface_id,
  criticality, detail_level, review_state, execution_mode,
  template, automation_content, milestone, created_by
)
SELECT v.slug,
       v.title,
       v.description,
       m.id,
       CASE WHEN v.surface_slug IS NULL THEN NULL
            ELSE (SELECT id FROM s WHERE module_id = m.id AND slug = v.surface_slug)
       END,
       v.criticality, 'l1', 'draft', 'integration',
       'standard', v.fingerprint, 'flow-seed-2026-05-20', 'claude-flow-seed'
FROM (VALUES
  ('flow', 'flow-page', 'flow.open-document', 'Open a document in Flow mode', '/document/:id mounts the prose editor for a known doc id.', '5939482fcdae5a4b', 'p0'),
  ('flow', 'flow-canvas', 'flow.type-prose-persists', 'Typed prose persists across a reload', 'Text typed into the canvas survives a reload of /document/:id.', '7177245871c91a9b', 'p0'),
  ('flow', 'flow-canvas', 'flow.autosave-debounced', 'Edits autosave after the debounce window', 'useAutoSave flushes a batched update ~3s after the last keystroke.', 'a0dc2fe884efe1c3', 'p0'),
  ('flow', 'block-flow-toggle', 'flow.toggle-to-block', 'Block/Flow toggle switches to Block mode', 'Clicking Block navigates /document/:id to /studio/:id for the same doc.', '7153cd20a4fb30ae', 'p0'),
  ('flow', 'block-flow-toggle', 'flow.toggle-to-flow', 'Block/Flow toggle switches to Flow mode', 'Clicking Flow navigates /studio/:id to /document/:id for the same doc.', '225d2596da56177e', 'p0'),
  ('flow', 'flow-canvas', 'flow.markdown-bold', 'Markdown input rule applies bold', 'Typing **text** marks the run bold in the prose canvas.', '8b35ac77d9223779', 'p1'),
  ('flow', 'flow-canvas', 'flow.markdown-italic', 'Markdown input rule applies italic', 'Typing *text* / _text_ marks the run italic in the prose canvas.', '6f4254976ccb2a67', 'p1'),
  ('flow', 'flow-canvas', 'flow.inline-math-renders', 'Inline math renders from $...$', 'Typing $x^2$ inline produces a KaTeX-rendered inline equation.', 'efb22fdf6d359978', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.slash-menu-opens', 'Slash menu opens on "/"', 'Pressing "/" in the canvas opens the slash command menu at the cursor.', '88f7440fc9310f48', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.slash-menu-filters', 'Slash menu filters as you type', 'Typing after "/" narrows the menu to matching block types.', '67fc7d2ed93f744a', 'p1'),
  ('flow', 'flow-toolbox', 'flow.toolbox-opens', 'Toolbox insert pane opens with all sections', 'The pinned Toolbox shows the 6 sections: text, lists, math, media, refs, layout.', '891521e9e7689363', 'p0'),
  ('flow', 'flow-toolbox', 'flow.toolbox-search-filters', 'Toolbox search filters insert items', 'Typing in the Toolbox search field narrows the visible block items.', '84a3b184a476f9d0', 'p1'),
  ('flow', 'flow-toolbox', 'flow.toolbox-insert-at-cursor', 'Toolbox item inserts a block at the cursor', 'Clicking a Toolbox item inserts that block at the current selection.', '17cb48ea33ab6672', 'p0'),
  ('flow', 'flow-ribbon', 'flow.ribbon-tab-switch', 'Ribbon tabs switch command groups', 'Switching Home/Cite/Review/View swaps the ribbon command set.', 'aa504f09bf747606', 'p2'),
  ('flow', 'flow-ribbon', 'flow.ribbon-format-bold', 'Ribbon Bold formats the selection', 'Selecting text and clicking ribbon Bold marks it bold.', '157fe99a07211b8d', 'p1'),
  ('flow', 'flow-outline-panel', 'flow.outline-lists-headings', 'Outline panel lists document headings', 'The outline reflects every heading in the prose document, in order.', '0b3661c3636e0493', 'p1'),
  ('flow', 'flow-outline-panel', 'flow.outline-click-scrolls', 'Clicking an outline entry scrolls the canvas', 'Selecting an outline heading scrolls the canvas to that section.', '43156119f9c53749', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.preview-renders', 'Preview panel renders the document', 'The preview pane shows a non-empty rendering of the prose document.', 'db996b4fc33ab6e9', 'p0'),
  ('flow', 'flow-preview-panel', 'flow.preview-toggle', 'Preview panel can be shown and hidden', 'The View ribbon toggle shows/hides the preview pane.', '29c71db31ecacc20', 'p1'),
  ('flow', 'flow-format-rail', 'flow.format-rail-opens', 'Format rail opens for the active block', 'The format rail shows formatting + config for the block at the cursor.', 'b1ee5bc7da3fdcc9', 'p1'),
  ('flow', 'flow-validate-rail', 'flow.validate-rail-lists-issues', 'Validate rail lists LaTeX validation issues', 'The validate rail enumerates validation issues for the document.', 'e5c848d20a328a76', 'p1'),
  ('flow', 'flow-command-palette', 'flow.command-palette-opens', 'Command palette opens on Cmd+K', 'Pressing Cmd/Ctrl+K opens the command palette over the prose editor.', 'e04bc0f3c3799296', 'p0'),
  ('flow', 'flow-command-palette', 'flow.command-palette-runs', 'Command palette runs a selected action', 'Choosing an action from the palette executes it and closes the palette.', 'e8232edfe4d0a0eb', 'p1'),
  ('flow', 'flow-activity-bar', 'flow.activity-bar-switch-panel', 'Activity bar switches the docked side panel', 'Clicking an activity-bar icon swaps the right-rail panel.', '3dd35dd2d24f5892', 'p1'),
  ('flow', 'flow-comments-panel', 'flow.comments-add-thread', 'A comment thread can be added in Flow mode', 'The comments panel composes a new thread on the prose document.', '4804ec0a4b0589fe', 'p1'),
  ('flow', 'flow-document-settings', 'flow.document-settings-opens', 'Document settings dialog opens from the topbar', 'Clicking the document stamp opens the class/font/paper settings dialog.', 'd1a379c25f7a391f', 'p1'),
  ('flow', 'flow-formula-panel', 'flow.formula-panel-inserts', 'Formula panel inserts a formula into the canvas', 'Picking a formula from the panel inserts it at the cursor.', 'd053fd810807ac47', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.paragraph.create-via-slash', 'Paragraph: create via slash command', NULL, 'cf2e47edea001e3b', 'p0'),
  ('flow', 'flow-toolbox', 'flow.paragraph.create-via-toolbox', 'Paragraph: create via toolbox pane', NULL, 'a197a27ddce0f44e', 'p1'),
  ('flow', 'flow-canvas', 'flow.paragraph.edit-inline', 'Paragraph: edit inline', NULL, 'fe5d3f4b922f7cca', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.paragraph.convert-via-slash', 'Paragraph: convert via slash command', NULL, '1908cf65eb20548b', 'p1'),
  ('flow', 'flow-canvas', 'flow.paragraph.delete-via-backspace', 'Paragraph: delete via backspace', NULL, '8656f30612ef8b96', 'p2'),
  ('flow', 'flow-canvas', 'flow.paragraph.reorder-via-drag', 'Paragraph: reorder via drag handle', NULL, '76f160dd85044586', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.paragraph.render-preview', 'Paragraph: render in preview pane', NULL, '539fe7f703ac48a7', 'p0'),
  ('export', 'export-dialog', 'flow.paragraph.export-to-latex', 'Paragraph: export to latex', NULL, '4ccc2116f7767a5a', 'p0'),
  ('export', 'export-dialog', 'flow.paragraph.export-to-markdown', 'Paragraph: export to markdown', NULL, '811583b0c825d3d6', 'p1'),
  ('flow', 'flow-canvas', 'flow.heading.create-via-markdown', 'Heading: create via markdown shortcut', NULL, 'eb633ddf2ecfee1b', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.heading.create-via-slash', 'Heading: create via slash command', NULL, '110858beabf6bcb5', 'p0'),
  ('flow', 'flow-toolbox', 'flow.heading.create-via-toolbox', 'Heading: create via toolbox pane', NULL, 'c0eeb42241413bc7', 'p1'),
  ('flow', 'flow-canvas', 'flow.heading.edit-inline', 'Heading: edit inline', NULL, 'f387c9a2e95117c0', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.heading.convert-via-slash', 'Heading: convert via slash command', NULL, '71fa83c4a0aa58c7', 'p1'),
  ('flow', 'flow-canvas', 'flow.heading.delete-via-backspace', 'Heading: delete via backspace', NULL, '6e7267dbb26f144c', 'p2'),
  ('flow', 'flow-canvas', 'flow.heading.reorder-via-drag', 'Heading: reorder via drag handle', NULL, '11b6a96af29105f9', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.heading.render-preview', 'Heading: render in preview pane', NULL, '85c859041e567aab', 'p0'),
  ('export', 'export-dialog', 'flow.heading.export-to-latex', 'Heading: export to latex', NULL, 'cb2a4d97b15bb096', 'p0'),
  ('export', 'export-dialog', 'flow.heading.export-to-markdown', 'Heading: export to markdown', NULL, 'a6a2247405a017b7', 'p1'),
  ('flow', 'flow-canvas', 'flow.list.create-via-markdown', 'List: create via markdown shortcut', NULL, '05908680d0a55ddc', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.list.create-via-slash', 'List: create via slash command', NULL, '87c52699cd309768', 'p0'),
  ('flow', 'flow-toolbox', 'flow.list.create-via-toolbox', 'List: create via toolbox pane', NULL, 'c78127686b3ebf8d', 'p1'),
  ('flow', 'flow-canvas', 'flow.list.edit-inline', 'List: edit inline', NULL, 'f08bc07e36994b92', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.list.convert-via-slash', 'List: convert via slash command', NULL, '9a059f353b62f4f4', 'p1'),
  ('flow', 'flow-canvas', 'flow.list.delete-via-backspace', 'List: delete via backspace', NULL, 'df3c4fc565ddeffb', 'p2'),
  ('flow', 'flow-canvas', 'flow.list.reorder-via-drag', 'List: reorder via drag handle', NULL, 'cc174f0d20fb566a', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.list.render-preview', 'List: render in preview pane', NULL, 'ff935dcbf5ce0605', 'p0'),
  ('export', 'export-dialog', 'flow.list.export-to-latex', 'List: export to latex', NULL, '9634abe0d3f3b896', 'p0'),
  ('export', 'export-dialog', 'flow.list.export-to-markdown', 'List: export to markdown', NULL, '2f34be3b36cded10', 'p1'),
  ('flow', 'flow-canvas', 'flow.blockquote.create-via-markdown', 'Block quote: create via markdown shortcut', NULL, '41ab0d3c6b5e9f69', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.blockquote.create-via-slash', 'Block quote: create via slash command', NULL, '57d2f8b169298737', 'p0'),
  ('flow', 'flow-toolbox', 'flow.blockquote.create-via-toolbox', 'Block quote: create via toolbox pane', NULL, 'b71212eb34d26fe6', 'p1'),
  ('flow', 'flow-canvas', 'flow.blockquote.edit-inline', 'Block quote: edit inline', NULL, '7b1ed0b04a397d53', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.blockquote.convert-via-slash', 'Block quote: convert via slash command', NULL, 'a7e07fc53b38fc23', 'p1'),
  ('flow', 'flow-canvas', 'flow.blockquote.delete-via-backspace', 'Block quote: delete via backspace', NULL, '41984b37f20da6e7', 'p2'),
  ('flow', 'flow-canvas', 'flow.blockquote.reorder-via-drag', 'Block quote: reorder via drag handle', NULL, '9cc66cf7611af72b', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.blockquote.render-preview', 'Block quote: render in preview pane', NULL, '239792c7df6a5f9d', 'p0'),
  ('export', 'export-dialog', 'flow.blockquote.export-to-latex', 'Block quote: export to latex', NULL, '44caaeae542122bd', 'p0'),
  ('export', 'export-dialog', 'flow.blockquote.export-to-markdown', 'Block quote: export to markdown', NULL, '1096afd6662ed52b', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.theorem.create-via-slash', 'Theorem: create via slash command', NULL, '1b413d0af7d7faee', 'p0'),
  ('flow', 'flow-toolbox', 'flow.theorem.create-via-toolbox', 'Theorem: create via toolbox pane', NULL, 'b594f2f70c52033f', 'p1'),
  ('flow', 'flow-canvas', 'flow.theorem.edit-inline', 'Theorem: edit inline', NULL, '53ee3ad0f94084cd', 'p0'),
  ('flow', 'flow-format-rail', 'flow.theorem.edit-via-drawer', 'Theorem: edit via format rail', NULL, 'c98e951b435548ea', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.theorem.convert-via-slash', 'Theorem: convert via slash command', NULL, '1b8b300279aa09ca', 'p1'),
  ('flow', 'flow-canvas', 'flow.theorem.delete-via-backspace', 'Theorem: delete via backspace', NULL, '7b3dbf0e67e4932c', 'p2'),
  ('flow', 'flow-canvas', 'flow.theorem.reorder-via-drag', 'Theorem: reorder via drag handle', NULL, 'bff69bc84c131364', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.theorem.render-preview', 'Theorem: render in preview pane', NULL, '37229ea6cc109080', 'p0'),
  ('export', 'export-dialog', 'flow.theorem.export-to-latex', 'Theorem: export to latex', NULL, '5b715599d0056539', 'p0'),
  ('export', 'export-dialog', 'flow.theorem.export-to-markdown', 'Theorem: export to markdown', NULL, '89c42ccee2143782', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.abstract.create-via-slash', 'Abstract: create via slash command', NULL, '356456aadca1616d', 'p0'),
  ('flow', 'flow-toolbox', 'flow.abstract.create-via-toolbox', 'Abstract: create via toolbox pane', NULL, 'df4cbe7fb521a22b', 'p1'),
  ('flow', 'flow-canvas', 'flow.abstract.edit-inline', 'Abstract: edit inline', NULL, '7ee32fca96495e5a', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.abstract.convert-via-slash', 'Abstract: convert via slash command', NULL, 'a3c51c2dbebe2693', 'p1'),
  ('flow', 'flow-canvas', 'flow.abstract.delete-via-backspace', 'Abstract: delete via backspace', NULL, '2cda6acfe8c75481', 'p2'),
  ('flow', 'flow-canvas', 'flow.abstract.reorder-via-drag', 'Abstract: reorder via drag handle', NULL, 'f842e9a121f782d3', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.abstract.render-preview', 'Abstract: render in preview pane', NULL, '3431c4542f2a4242', 'p0'),
  ('export', 'export-dialog', 'flow.abstract.export-to-latex', 'Abstract: export to latex', NULL, 'f7615f0bc2e4e515', 'p0'),
  ('export', 'export-dialog', 'flow.abstract.export-to-markdown', 'Abstract: export to markdown', NULL, '3525d68c2c3c743d', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.figure.create-via-slash', 'Figure: create via slash command', NULL, 'dc4960096d86ec91', 'p0'),
  ('flow', 'flow-toolbox', 'flow.figure.create-via-toolbox', 'Figure: create via toolbox pane', NULL, 'dcaa6acaa212b7e6', 'p1'),
  ('flow', 'flow-format-rail', 'flow.figure.edit-via-drawer', 'Figure: edit via format rail', NULL, 'bb0f42634c517f77', 'p1'),
  ('flow', 'flow-canvas', 'flow.figure.reorder-via-drag', 'Figure: reorder via drag handle', NULL, 'f10a817b56b73dc2', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.figure.render-preview', 'Figure: render in preview pane', NULL, '3ad8dc5789077f80', 'p0'),
  ('export', 'export-dialog', 'flow.figure.export-to-latex', 'Figure: export to latex', NULL, 'e45e3be1c7ed09ac', 'p0'),
  ('export', 'export-dialog', 'flow.figure.export-to-markdown', 'Figure: export to markdown', NULL, '32b63c137d7e5dfb', 'p1'),
  ('flow', 'flow-canvas', 'flow.equation.create-via-markdown', 'Equation: create via markdown shortcut', NULL, '0a851ab34e38175e', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.equation.create-via-slash', 'Equation: create via slash command', NULL, '058b917da35f324c', 'p0'),
  ('flow', 'flow-toolbox', 'flow.equation.create-via-toolbox', 'Equation: create via toolbox pane', NULL, 'ba90e085cbbef878', 'p1'),
  ('flow', 'flow-formula-panel', 'flow.equation.edit-via-formula-editor', 'Equation: edit via formula editor', NULL, '31c46485a73278e9', 'p0'),
  ('flow', 'flow-canvas', 'flow.equation.reorder-via-drag', 'Equation: reorder via drag handle', NULL, 'cfd63fc4052afb58', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.equation.render-preview', 'Equation: render in preview pane', NULL, 'bd0cfe9ff5d7fa2e', 'p0'),
  ('export', 'export-dialog', 'flow.equation.export-to-latex', 'Equation: export to latex', NULL, '03973ce16820d428', 'p0'),
  ('export', 'export-dialog', 'flow.equation.export-to-markdown', 'Equation: export to markdown', NULL, '31fb75bb508db0c2', 'p1'),
  ('flow', 'flow-canvas', 'flow.code.create-via-markdown', 'Code: create via markdown shortcut', NULL, '1b301cc972d17f27', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.code.create-via-slash', 'Code: create via slash command', NULL, 'd4c0953ebe45c9d8', 'p0'),
  ('flow', 'flow-toolbox', 'flow.code.create-via-toolbox', 'Code: create via toolbox pane', NULL, '207a9d4968fb6f78', 'p1'),
  ('flow', 'flow-canvas', 'flow.code.edit-inline', 'Code: edit inline', NULL, '39753474018f7776', 'p0'),
  ('flow', 'flow-format-rail', 'flow.code.edit-via-drawer', 'Code: edit via format rail', NULL, '3559bb1ef7f70e6b', 'p1'),
  ('flow', 'flow-canvas', 'flow.code.delete-via-backspace', 'Code: delete via backspace', NULL, 'b7fff9db0e12097f', 'p2'),
  ('flow', 'flow-canvas', 'flow.code.reorder-via-drag', 'Code: reorder via drag handle', NULL, '14654392f78c6e94', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.code.render-preview', 'Code: render in preview pane', NULL, '620a807db348d91e', 'p0'),
  ('export', 'export-dialog', 'flow.code.export-to-latex', 'Code: export to latex', NULL, 'ef02fd6718ca7dd7', 'p0'),
  ('export', 'export-dialog', 'flow.code.export-to-markdown', 'Code: export to markdown', NULL, '1c1958d273bcb3d5', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.table.create-via-slash', 'Table: create via slash command', NULL, '65135b4106be47ad', 'p0'),
  ('flow', 'flow-toolbox', 'flow.table.create-via-toolbox', 'Table: create via toolbox pane', NULL, '8e2cde41c18cd3b2', 'p1'),
  ('flow', 'flow-format-rail', 'flow.table.edit-via-drawer', 'Table: edit via format rail', NULL, 'dd1573a714c4d11e', 'p1'),
  ('flow', 'flow-canvas', 'flow.table.reorder-via-drag', 'Table: reorder via drag handle', NULL, '5371c156a68c20e0', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.table.render-preview', 'Table: render in preview pane', NULL, '9a6970a443b68e27', 'p0'),
  ('export', 'export-dialog', 'flow.table.export-to-latex', 'Table: export to latex', NULL, '86eccfef966453c8', 'p0'),
  ('export', 'export-dialog', 'flow.table.export-to-markdown', 'Table: export to markdown', NULL, '1bb6fd1017984c29', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.bibliography.create-via-slash', 'Bibliography: create via slash command', NULL, '422844a8cec96cfc', 'p0'),
  ('flow', 'flow-toolbox', 'flow.bibliography.create-via-toolbox', 'Bibliography: create via toolbox pane', NULL, '01f22142cbc4930c', 'p1'),
  ('flow', 'flow-canvas', 'flow.bibliography.reorder-via-drag', 'Bibliography: reorder via drag handle', NULL, '477fd273db98c631', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.bibliography.render-preview', 'Bibliography: render in preview pane', NULL, '0e445b2487524a66', 'p0'),
  ('export', 'export-dialog', 'flow.bibliography.export-to-latex', 'Bibliography: export to latex', NULL, 'baf7626ff9a7bb55', 'p0'),
  ('export', 'export-dialog', 'flow.bibliography.export-to-markdown', 'Bibliography: export to markdown', NULL, '257156c3c1383cc1', 'p1'),
  ('flow', 'flow-slash-menu', 'flow.tableOfContents.create-via-slash', 'Table of contents: create via slash command', NULL, '07f4c4e83b3d9d2a', 'p0'),
  ('flow', 'flow-toolbox', 'flow.tableOfContents.create-via-toolbox', 'Table of contents: create via toolbox pane', NULL, '35e7f761f3accab8', 'p1'),
  ('flow', 'flow-canvas', 'flow.tableOfContents.reorder-via-drag', 'Table of contents: reorder via drag handle', NULL, '8106126c4b81de58', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.tableOfContents.render-preview', 'Table of contents: render in preview pane', NULL, 'ab2b1c736d55cb92', 'p0'),
  ('export', 'export-dialog', 'flow.tableOfContents.export-to-latex', 'Table of contents: export to latex', NULL, '967e6cb545208c55', 'p0'),
  ('export', 'export-dialog', 'flow.tableOfContents.export-to-markdown', 'Table of contents: export to markdown', NULL, '5d14adf6ea2d3894', 'p1'),
  ('flow', 'flow-canvas', 'flow.pageBreak.create-via-markdown', 'Page break: create via markdown shortcut', NULL, '47cdd2737e77f1c5', 'p0'),
  ('flow', 'flow-slash-menu', 'flow.pageBreak.create-via-slash', 'Page break: create via slash command', NULL, '9f8263add3144c25', 'p0'),
  ('flow', 'flow-toolbox', 'flow.pageBreak.create-via-toolbox', 'Page break: create via toolbox pane', NULL, '9f721368c5507dfe', 'p1'),
  ('flow', 'flow-canvas', 'flow.pageBreak.reorder-via-drag', 'Page break: reorder via drag handle', NULL, '585f3809e869a37e', 'p1'),
  ('flow', 'flow-preview-panel', 'flow.pageBreak.render-preview', 'Page break: render in preview pane', NULL, 'c9f9964682bf4baf', 'p0'),
  ('export', 'export-dialog', 'flow.pageBreak.export-to-latex', 'Page break: export to latex', NULL, '90c23eb4f10a3e3a', 'p0'),
  ('export', 'export-dialog', 'flow.pageBreak.export-to-markdown', 'Page break: export to markdown', NULL, '811fcc06e170f1c6', 'p1')
) AS v(module_slug, surface_slug, slug, title, description, fingerprint, criticality)
JOIN m ON m.slug = v.module_slug
ON CONFLICT (slug) DO NOTHING;

-- Insert version 1 (L1, generated) for every seeded scenario.
INSERT INTO e2e.scenario_version (
  scenario_id, version_number, detail_level, title, description,
  steps, generation_provenance, generated_by
)
SELECT
  sc.id, 1, 'l1', sc.title, sc.description,
  '[]'::jsonb, 'llm_draft', 'claude-flow-seed'
FROM e2e.scenario sc
WHERE sc.milestone = 'flow-seed-2026-05-20'
  AND NOT EXISTS (
    SELECT 1 FROM e2e.scenario_version v
    WHERE v.scenario_id = sc.id AND v.version_number = 1
  );

-- Wire current_version_id pointer.
UPDATE e2e.scenario sc
SET current_version_id = v.id, updated_at = NOW()
FROM e2e.scenario_version v
WHERE v.scenario_id = sc.id
  AND v.version_number = 1
  AND sc.current_version_id IS DISTINCT FROM v.id
  AND sc.milestone = 'flow-seed-2026-05-20';

DO $$
DECLARE c INTEGER;
BEGIN
  SELECT COUNT(*) INTO c FROM e2e.scenario WHERE milestone = 'flow-seed-2026-05-20';
  RAISE NOTICE 'flow scenarios in DB: %', c;
END$$;

COMMIT;
