-- =====================================================================
--  Scenario System — collaboration & reuse scenarios.
--
--  GENERATED by lilia-scenario-system/scripts/seed-collab-scenarios.mjs.
--  Adds the `teams` module and 25 authored-L2 scenarios for
--  Teams, Templates and Sharing — derived from the editor's real
--  operations (useTeams / useTemplates hooks, sharing components).
--
--  Idempotent: modules and scenarios guarded by NOT EXISTS on slug.
-- =====================================================================

BEGIN;

-- New modules.
INSERT INTO e2e.module (id, slug, name, description, criticality, is_active, created_at, updated_at)
SELECT gen_random_uuid(), 'teams', 'Teams & collaboration', 'Team creation, membership, roles and team documents.', 'p1', true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM e2e.module WHERE slug = 'teams');

-- New scenarios + their L2 versions.
WITH cat (slug, module_slug, criticality, title, descr, automation_content, steps) AS (
  VALUES
  ('teams.list-teams', 'teams', 'p1', 'Your teams are listed', 'Open the Teams page and see every team you belong to.', 'a3af9664197a00b3', '[{"step_kind":"setup","description":"Open the Teams page.","user_visible_outcome":"The Teams page loads."},{"step_kind":"assert","description":"Every team you belong to is listed.","user_visible_outcome":"Each team shows its name and a way to open it."}]'::jsonb),
  ('teams.create-team', 'teams', 'p0', 'Create a team', 'Create a new team from the Teams page.', '3a77b00ce1403458', '[{"step_kind":"setup","description":"Open the Teams page.","user_visible_outcome":"The Teams page loads."},{"step_kind":"action","action_kind":"click","description":"Click New team."},{"step_kind":"action","action_kind":"type","description":"Enter a name for the team."},{"step_kind":"action","action_kind":"click","description":"Confirm the creation."},{"step_kind":"assert","description":"The team is created.","user_visible_outcome":"The new team appears in your teams list."}]'::jsonb),
  ('teams.rename-team', 'teams', 'p1', 'Rename a team', 'Change a team’s name from its manage dialog.', '403d06890f887cd8', '[{"step_kind":"setup","description":"Open a team you own.","user_visible_outcome":"The team detail page is shown."},{"step_kind":"action","action_kind":"click","description":"Open the team’s manage dialog."},{"step_kind":"action","action_kind":"type","description":"Change the team name."},{"step_kind":"action","action_kind":"click","description":"Save."},{"step_kind":"assert","description":"The team is renamed.","user_visible_outcome":"The team shows the new name everywhere it appears."}]'::jsonb),
  ('teams.delete-team', 'teams', 'p1', 'Delete a team', 'Delete a team you own.', 'b881a8440a8cc3d6', '[{"step_kind":"setup","description":"Open the manage dialog of a team you own.","user_visible_outcome":"The manage dialog is shown."},{"step_kind":"action","action_kind":"click","description":"Choose Delete team and confirm."},{"step_kind":"assert","description":"The team is deleted.","user_visible_outcome":"The team no longer appears in your teams list."}]'::jsonb),
  ('teams.open-team-detail', 'teams', 'p1', 'Open a team’s detail page', 'Open a team to see its members and documents.', '189327cf73cd70fa', '[{"step_kind":"setup","description":"Open the Teams page.","user_visible_outcome":"The Teams page loads."},{"step_kind":"action","action_kind":"click","description":"Click a team."},{"step_kind":"assert","description":"The team detail page opens.","user_visible_outcome":"It shows the team’s members and documents."}]'::jsonb),
  ('teams.list-members', 'teams', 'p1', 'A team’s members are listed', 'See the members of a team and their roles.', 'a08086aaf73641c6', '[{"step_kind":"setup","description":"Open a team’s detail page.","user_visible_outcome":"The team detail page is shown."},{"step_kind":"assert","description":"The members section lists every member.","user_visible_outcome":"Each member shows their role."}]'::jsonb),
  ('teams.invite-member', 'teams', 'p0', 'Invite a member to a team', 'Invite someone to a team by email.', '491147f367252cce', '[{"step_kind":"setup","description":"Open a team’s detail page as an owner or admin.","user_visible_outcome":"The team detail page is shown."},{"step_kind":"action","action_kind":"click","description":"Open the invite control."},{"step_kind":"action","action_kind":"type","description":"Enter the invitee’s email and pick a role."},{"step_kind":"action","action_kind":"click","description":"Send the invite."},{"step_kind":"assert","description":"The invite is sent.","user_visible_outcome":"The invitee appears as a pending member."}]'::jsonb),
  ('teams.change-member-role', 'teams', 'p1', 'Change a member’s role', 'Change the role of an existing team member.', 'f186240c91072a56', '[{"step_kind":"setup","description":"Open a team’s detail page as an owner or admin.","user_visible_outcome":"The members list is shown."},{"step_kind":"action","action_kind":"click","description":"Open a member’s role control."},{"step_kind":"action","action_kind":"click","description":"Pick a different role."},{"step_kind":"assert","description":"The member’s role is updated.","user_visible_outcome":"The members list shows the new role."}]'::jsonb),
  ('teams.remove-member', 'teams', 'p1', 'Remove a member from a team', 'Remove a member from a team.', 'e2af673e7cf8c21e', '[{"step_kind":"setup","description":"Open a team’s detail page as an owner or admin.","user_visible_outcome":"The members list is shown."},{"step_kind":"action","action_kind":"click","description":"Open a member’s actions and choose Remove."},{"step_kind":"assert","description":"The member is removed.","user_visible_outcome":"The member no longer appears in the team."}]'::jsonb),
  ('teams.list-team-documents', 'teams', 'p1', 'A team’s documents are listed', 'See the documents shared with a team.', '98d80367739e6c43', '[{"step_kind":"setup","description":"Open a team’s detail page.","user_visible_outcome":"The team detail page is shown."},{"step_kind":"assert","description":"The documents section lists the team’s documents.","user_visible_outcome":"Each document can be opened from the team."}]'::jsonb),
  ('teams.switch-active-team', 'teams', 'p1', 'Switch the active team', 'Switch which team the current view is scoped to.', '5e439f8a91bed8d0', '[{"step_kind":"setup","description":"Open the dashboard or editor with the team switcher visible.","user_visible_outcome":"The team switcher chip is shown."},{"step_kind":"action","action_kind":"click","description":"Open the team switcher chip."},{"step_kind":"action","action_kind":"click","description":"Choose a different team."},{"step_kind":"assert","description":"The active team switches.","user_visible_outcome":"The view re-scopes to the chosen team."}]'::jsonb),
  ('teams.manage-dialog-opens', 'teams', 'p2', 'The team manage dialog opens', 'Open the team manage dialog.', '9f5be59ab971acc0', '[{"step_kind":"setup","description":"Open a team you own.","user_visible_outcome":"The team detail page is shown."},{"step_kind":"action","action_kind":"click","description":"Open the team’s manage dialog."},{"step_kind":"assert","description":"The manage dialog opens.","user_visible_outcome":"It shows the team’s settings."}]'::jsonb),
  ('templates.browse-gallery', 'templates', 'p1', 'Browse the templates gallery', 'Open the Templates gallery and see the available templates.', '9271ff32f38fae38', '[{"step_kind":"setup","description":"Open the Templates page.","user_visible_outcome":"The Templates gallery loads."},{"step_kind":"assert","description":"The gallery lists the available templates.","user_visible_outcome":"Each template shows a preview and its name."}]'::jsonb),
  ('templates.filter-by-category', 'templates', 'p2', 'Filter templates by category', 'Narrow the templates gallery to one category.', '886f94b8e19ff144', '[{"step_kind":"setup","description":"Open the Templates page.","user_visible_outcome":"The Templates gallery loads."},{"step_kind":"action","action_kind":"click","description":"Pick a category."},{"step_kind":"assert","description":"The gallery is filtered.","user_visible_outcome":"Only templates in that category are shown."}]'::jsonb),
  ('templates.open-template-detail', 'templates', 'p2', 'Open a template’s detail', 'Open a template to see its detail.', '48ee266b93c70222', '[{"step_kind":"setup","description":"Open the Templates page.","user_visible_outcome":"The Templates gallery loads."},{"step_kind":"action","action_kind":"click","description":"Click a template."},{"step_kind":"assert","description":"The template detail opens.","user_visible_outcome":"It shows the template’s contents and metadata."}]'::jsonb),
  ('templates.create-document-from-template', 'templates', 'p0', 'Create a document from a template', 'Start a new document from a template.', '2aa76b44e5721139', '[{"step_kind":"setup","description":"Open the Templates page.","user_visible_outcome":"The Templates gallery loads."},{"step_kind":"action","action_kind":"click","description":"Choose a template and select Use template."},{"step_kind":"assert","description":"A new document is created from the template.","user_visible_outcome":"The document opens in the editor pre-filled from the template."}]'::jsonb),
  ('templates.save-document-as-template', 'templates', 'p1', 'Save a document as a template', 'Save the current document as a reusable template.', '4d93a8873ba53254', '[{"step_kind":"setup","description":"Open a document in the editor.","user_visible_outcome":"The editor is ready."},{"step_kind":"action","action_kind":"click","description":"Click Save as template in the ribbon."},{"step_kind":"action","action_kind":"type","description":"Give the template a name and category."},{"step_kind":"action","action_kind":"click","description":"Save."},{"step_kind":"assert","description":"The document is saved as a template.","user_visible_outcome":"It appears in the Templates gallery."}]'::jsonb),
  ('templates.create-template', 'templates', 'p2', 'Create a template', 'Create a new template in the gallery.', 'a39584c59b82a7d6', '[{"step_kind":"setup","description":"Open the Templates page.","user_visible_outcome":"The Templates gallery loads."},{"step_kind":"action","action_kind":"click","description":"Choose New template."},{"step_kind":"action","action_kind":"type","description":"Fill in the template’s name and category."},{"step_kind":"action","action_kind":"click","description":"Create."},{"step_kind":"assert","description":"The template is created.","user_visible_outcome":"The new template appears in the gallery."}]'::jsonb),
  ('templates.delete-template', 'templates', 'p2', 'Delete a template', 'Delete a template you own.', 'b50a838205eeaff3', '[{"step_kind":"setup","description":"Open the Templates page.","user_visible_outcome":"The Templates gallery loads."},{"step_kind":"action","action_kind":"click","description":"Open a template you own and choose Delete."},{"step_kind":"assert","description":"The template is deleted.","user_visible_outcome":"It no longer appears in the gallery."}]'::jsonb),
  ('share.open-share-drawer', 'share', 'p0', 'Open the share drawer', 'Open the sharing options for a document.', 'a7901499ea682a8a', '[{"step_kind":"setup","description":"Open a document in the editor.","user_visible_outcome":"The editor is ready."},{"step_kind":"action","action_kind":"click","description":"Click Share."},{"step_kind":"assert","description":"The share drawer opens.","user_visible_outcome":"It shows the document’s sharing options."}]'::jsonb),
  ('share.create-share-link', 'share', 'p0', 'Create a public share link', 'Generate a shareable link for a document.', '5961688f9856ab6e', '[{"step_kind":"setup","description":"Open the share drawer for a document.","user_visible_outcome":"The share drawer is open."},{"step_kind":"action","action_kind":"click","description":"Enable link sharing."},{"step_kind":"assert","description":"A share link is generated.","user_visible_outcome":"The link can be copied and opened by anyone who has it."}]'::jsonb),
  ('share.share-with-team', 'share', 'p1', 'Share a document with a team', 'Give a team access to a document.', '8e3fd0d8fce2e5a2', '[{"step_kind":"setup","description":"Open the share drawer for a document.","user_visible_outcome":"The share drawer is open."},{"step_kind":"action","action_kind":"click","description":"In the Team access section, choose a team."},{"step_kind":"assert","description":"The document is shared with the team.","user_visible_outcome":"Team members can open the document."}]'::jsonb),
  ('share.set-permission', 'share', 'p1', 'Set a collaborator’s permission', 'Change whether a collaborator can view or edit.', 'a9d63397ca610588', '[{"step_kind":"setup","description":"Open the share drawer for a shared document.","user_visible_outcome":"The share drawer lists the collaborators."},{"step_kind":"action","action_kind":"click","description":"Change a collaborator’s permission between view and edit."},{"step_kind":"assert","description":"The permission is updated.","user_visible_outcome":"The collaborator’s access level changes accordingly."}]'::jsonb),
  ('share.open-shared-document', 'share', 'p1', 'Open a shared document', 'Open a document from a share link.', '921108e1fb125133', '[{"step_kind":"setup","description":"Have a share link to a document.","user_visible_outcome":"The link is ready to open."},{"step_kind":"action","action_kind":"click","description":"Open the share link."},{"step_kind":"assert","description":"The shared document opens.","user_visible_outcome":"It loads in the shared-document viewer."}]'::jsonb),
  ('share.revoke-access', 'share', 'p1', 'Revoke sharing', 'Remove a collaborator or disable a document’s share link.', '0745d06c70063f8b', '[{"step_kind":"setup","description":"Open the share drawer for a shared document.","user_visible_outcome":"The share drawer is open."},{"step_kind":"action","action_kind":"click","description":"Remove a collaborator, or disable the share link."},{"step_kind":"assert","description":"Access is revoked.","user_visible_outcome":"The removed collaborator or link can no longer open the document."}]'::jsonb)
),
ins AS (
  INSERT INTO e2e.scenario (
    id, slug, title, description, module_id, criticality, detail_level,
    review_state, execution_mode, template, automation_content,
    is_deleted, created_at, updated_at, created_by
  )
  SELECT gen_random_uuid(), c.slug, c.title, c.descr, m.id, c.criticality, 'l2',
         'draft', 'integration', 'standard', c.automation_content,
         false, NOW(), NOW(), 'claude-collab-seed'
  FROM cat c
  JOIN e2e.module m ON m.slug = c.module_slug
  WHERE NOT EXISTS (SELECT 1 FROM e2e.scenario s WHERE s.slug = c.slug)
  RETURNING id, slug
)
INSERT INTO e2e.scenario_version (
  scenario_id, version_number, detail_level, title, description,
  steps, generation_provenance, generated_by
)
SELECT i.id, 1, 'l2', c.title, c.descr, c.steps, 'llm_draft', 'claude-collab-seed'
FROM ins i
JOIN cat c ON c.slug = i.slug;

-- Point each new scenario at its version.
UPDATE e2e.scenario s
SET current_version_id = v.id, updated_at = NOW()
FROM e2e.scenario_version v
WHERE v.scenario_id = s.id
  AND v.version_number = 1
  AND s.created_by = 'claude-collab-seed'
  AND s.current_version_id IS NULL;

DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM e2e.scenario WHERE created_by = 'claude-collab-seed' AND NOT is_deleted;
  RAISE NOTICE 'collaboration scenarios in catalogue: %', n;
END$$;

COMMIT;
