-- =====================================================================
--  Scenario System — journey scenarios (multi-step combinations).
--
--  GENERATED by lilia-scenario-system/scripts/seed-journey-scenarios.mjs.
--  Adds the `journeys` module and 6 authored-L2 journey
--  scenarios — realistic end-to-end workflows that combine atomic
--  scenarios. These are the natural candidates for tutorial video.
--
--  Idempotent: modules and scenarios guarded by NOT EXISTS on slug.
-- =====================================================================

BEGIN;

INSERT INTO e2e.module (id, slug, name, description, criticality, is_active, created_at, updated_at)
SELECT gen_random_uuid(), 'journeys', 'User journeys', 'Multi-step workflows that combine atomic scenarios end to end.', 'p1', true, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM e2e.module WHERE slug = 'journeys');

WITH cat (slug, module_slug, criticality, title, descr, automation_content, steps) AS (
  VALUES
  ('journeys.compose-structured-document', 'journeys', 'p0', 'Compose a structured document', 'Build a document from several block types — title, heading, prose, equation and a list.', '098488e6b2cac351', '[{"step_kind":"setup","description":"Open a new document in the Flow editor.","user_visible_outcome":"The continuous-prose canvas is ready."},{"step_kind":"action","action_kind":"type","description":"Type the document’s title on the first line."},{"step_kind":"action","action_kind":"type","description":"Press Enter, type \"# \" and a section heading.","user_visible_outcome":"The line becomes a heading."},{"step_kind":"action","action_kind":"type","description":"Press Enter and write an introductory paragraph."},{"step_kind":"action","action_kind":"type","description":"On a new line, type \"/\" and insert an Equation block."},{"step_kind":"action","action_kind":"type","description":"Below it, add a bulleted list of key points."},{"step_kind":"assert","description":"The document is a structured draft.","user_visible_outcome":"It now has a title, a heading, prose, an equation and a list."}]'::jsonb),
  ('journeys.build-heading-outline', 'journeys', 'p1', 'Build a heading outline and navigate it', 'Create a heading hierarchy and use the outline panel to navigate it.', 'b1d7884f7e8cc56b', '[{"step_kind":"setup","description":"Open a document in the Flow editor.","user_visible_outcome":"The canvas is ready."},{"step_kind":"action","action_kind":"type","description":"Create a top-level heading with \"# \"."},{"step_kind":"action","action_kind":"type","description":"Add a sub-heading with \"## \" and a third level with \"### \"."},{"step_kind":"action","action_kind":"click","description":"Open the Outline panel in the right rail.","user_visible_outcome":"The outline lists the heading hierarchy."},{"step_kind":"action","action_kind":"click","description":"Click an outline entry."},{"step_kind":"assert","description":"The canvas scrolls to the chosen heading.","user_visible_outcome":"The outline mirrors the document structure and navigates it."}]'::jsonb),
  ('journeys.slash-insert-sequence', 'journeys', 'p1', 'Insert a sequence of blocks via the slash menu', 'Insert several different block types one after another with the slash command menu.', '4d27805b24d43450', '[{"step_kind":"setup","description":"Open a document in the Flow editor.","user_visible_outcome":"The canvas is ready."},{"step_kind":"action","action_kind":"click","description":"Click into the canvas to place the cursor."},{"step_kind":"action","action_kind":"type","description":"Type \"/\" and insert a Heading."},{"step_kind":"action","action_kind":"type","description":"On a new line, slash-insert a Quote."},{"step_kind":"action","action_kind":"type","description":"Slash-insert a Code block."},{"step_kind":"action","action_kind":"type","description":"Slash-insert a List."},{"step_kind":"assert","description":"Four block types were inserted in sequence.","user_visible_outcome":"The slash menu builds a document quickly without leaving the keyboard."}]'::jsonb),
  ('journeys.write-with-live-preview', 'journeys', 'p1', 'Write with the LaTeX preview open', 'Compose content with the split LaTeX preview visible and watch it update live.', 'f56e548ea247d77e', '[{"step_kind":"setup","description":"Open a document in the Flow editor with the split LaTeX preview shown.","user_visible_outcome":"The canvas and the preview pane sit side by side."},{"step_kind":"action","action_kind":"type","description":"Type a section heading in the canvas."},{"step_kind":"action","action_kind":"type","description":"Write a paragraph below it."},{"step_kind":"action","action_kind":"type","description":"Add a $...$ inline-math expression."},{"step_kind":"assert","description":"The LaTeX preview reflects every edit.","user_visible_outcome":"The preview pane mirrors the document as it is written."}]'::jsonb),
  ('journeys.flow-block-roundtrip', 'journeys', 'p0', 'Move a document between Flow and Block mode', 'Write in the Flow editor, switch to the block-cards Studio and back, content intact.', 'ec32967a2f3a4849', '[{"step_kind":"setup","description":"Open a document in the Flow editor.","user_visible_outcome":"The canvas is ready."},{"step_kind":"action","action_kind":"type","description":"Write a heading and a paragraph."},{"step_kind":"action","action_kind":"click","description":"Switch to Block mode with the Block / Flow toggle."},{"step_kind":"assert","description":"The document opens in the block-cards Studio.","user_visible_outcome":"The same content is shown as block cards."},{"step_kind":"action","action_kind":"click","description":"Switch back to Flow mode."},{"step_kind":"assert","description":"The document returns to the Flow editor.","user_visible_outcome":"The content survived the round-trip intact."}]'::jsonb),
  ('journeys.draft-math-section', 'journeys', 'p1', 'Draft a math-heavy section', 'Draft a section combining a heading, prose with inline math, a display equation and a theorem.', '4ca00ebb74fadf1d', '[{"step_kind":"setup","description":"Open a document in the Flow editor.","user_visible_outcome":"The canvas is ready."},{"step_kind":"action","action_kind":"type","description":"Type a section heading for the math section."},{"step_kind":"action","action_kind":"type","description":"Write a paragraph containing an inline-math $x$ expression."},{"step_kind":"action","action_kind":"type","description":"Slash-insert a display Equation block."},{"step_kind":"action","action_kind":"type","description":"Slash-insert a Theorem block and write its statement."},{"step_kind":"assert","description":"A math-heavy section is drafted.","user_visible_outcome":"It combines a heading, prose with inline math, a display equation and a theorem."}]'::jsonb)
),
ins AS (
  INSERT INTO e2e.scenario (
    id, slug, title, description, module_id, criticality, detail_level,
    review_state, execution_mode, template, automation_content,
    is_deleted, created_at, updated_at, created_by
  )
  SELECT gen_random_uuid(), c.slug, c.title, c.descr, m.id, c.criticality, 'l2',
         'draft', 'integration', 'standard', c.automation_content,
         false, NOW(), NOW(), 'claude-journey-seed'
  FROM cat c
  JOIN e2e.module m ON m.slug = c.module_slug
  WHERE NOT EXISTS (SELECT 1 FROM e2e.scenario s WHERE s.slug = c.slug)
  RETURNING id, slug
)
INSERT INTO e2e.scenario_version (
  scenario_id, version_number, detail_level, title, description,
  steps, generation_provenance, generated_by
)
SELECT i.id, 1, 'l2', c.title, c.descr, c.steps, 'llm_draft', 'claude-journey-seed'
FROM ins i
JOIN cat c ON c.slug = i.slug;

UPDATE e2e.scenario s
SET current_version_id = v.id, updated_at = NOW()
FROM e2e.scenario_version v
WHERE v.scenario_id = s.id
  AND v.version_number = 1
  AND s.created_by = 'claude-journey-seed'
  AND s.current_version_id IS NULL;

DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM e2e.scenario WHERE created_by = 'claude-journey-seed' AND NOT is_deleted;
  RAISE NOTICE 'journey scenarios in catalogue: %', n;
END$$;

COMMIT;
