-- =====================================================================
--  Scenario System — close the v0 coverage gaps.
--
--  GENERATED by lilia-scenario-system/scripts/seed-coverage-gaps.mjs.
--
--  Part A — L1 → L2: rewrite the current version of two flow scenarios
--                    that still had steps=[]. L3 tests already exist;
--                    this just gives the catalogue real prose.
--  Part B — Populate 4 empty modules (admin / bibliography / formulas /
--           settings) with 15 authored-L2 scenarios derived
--           from real shipped surfaces.
--
--  Idempotent: NEW scenarios are guarded by NOT EXISTS on slug. L1→L2
--  promotions only fire when the current version's detail_level is
--  still 'l1' (so re-running this is a no-op once promoted).
-- =====================================================================

BEGIN;

-- ── Part A — L1 → L2 promotions ─────────────────────────────────────
WITH promo (slug, new_title, new_descr, new_steps) AS (
  VALUES
  ('flow.document-settings-opens', 'Open document settings', 'From the flow editor, open the Document settings drawer and confirm it mounts.', '[{"step_kind":"setup","description":"Open any document in the flow editor.","user_visible_outcome":"The flow editor is editable."},{"step_kind":"action","action_kind":"click","description":"Open the side rail and click Document settings."},{"step_kind":"assert","description":"The Document settings drawer mounts.","user_visible_outcome":"Title, metadata and document-level options are visible."}]'::jsonb),
  ('flow.validate-rail-lists-issues', 'Validate rail lists document issues', 'Open the Validate rail and confirm it lists the current document’s validation issues (or shows the clean state).', '[{"step_kind":"setup","description":"Open a document that includes at least one block.","user_visible_outcome":"The flow editor is editable with content."},{"step_kind":"action","action_kind":"click","description":"Open the side rail and switch to the Validate tab."},{"step_kind":"assert","description":"The validate rail lists every issue keyed by block.","user_visible_outcome":"Or the clean state message (\"no issues\") is shown when there are none."}]'::jsonb)
)
UPDATE e2e.scenario_version v
SET steps          = p.new_steps,
    title          = p.new_title,
    description    = p.new_descr,
    detail_level   = 'l2',
    generation_provenance = 'llm_draft',
    generated_by   = 'claude-coverage-gaps'
FROM promo p
JOIN e2e.scenario s ON s.slug = p.slug
WHERE v.id = s.current_version_id
  AND v.detail_level = 'l1';

-- Mirror the version-level bump back onto the scenario row so the
-- detail_level high-water mark is consistent.
UPDATE e2e.scenario s
SET detail_level = 'l2',
    updated_at   = NOW()
FROM e2e.scenario_version v
WHERE s.current_version_id = v.id
  AND v.detail_level = 'l2'
  AND s.detail_level = 'l1';

-- ── Part B — New scenarios for 4 empty modules ──────────────────────
WITH cat (slug, module_slug, criticality, title, descr, automation_content, steps) AS (
  VALUES
  ('admin.scenarios-list-loads', 'admin', 'p2', 'Internal scenarios list loads', 'Open /internal/scenarios and confirm the catalogue list mounts.', '92e4c35f9b2c3db7', '[{"step_kind":"setup","description":"Sign in with an admin account."},{"step_kind":"action","action_kind":"navigate","description":"Go to /internal/scenarios."},{"step_kind":"assert","description":"The scenarios list renders.","user_visible_outcome":"Module + L1/L2/L3 columns are present and at least one row appears."}]'::jsonb),
  ('admin.scenario-detail-opens', 'admin', 'p2', 'Open scenario detail', 'From the list, click a scenario and confirm its detail page (steps, history, results) loads.', '0fb6c4c62ddbb646', '[{"step_kind":"setup","description":"Open the /internal/scenarios list."},{"step_kind":"action","action_kind":"click","description":"Click any scenario row."},{"step_kind":"assert","description":"The detail view mounts.","user_visible_outcome":"Steps, version history and the recent result table are all rendered."}]'::jsonb),
  ('admin.review-pending-scenario', 'admin', 'p1', 'Approve a draft scenario', 'A draft (review_state=draft) scenario is approvable in the admin UI.', '6b3b7ad0de670c81', '[{"step_kind":"setup","description":"Open a draft scenario in /internal/scenarios."},{"step_kind":"action","action_kind":"click","description":"Click Approve."},{"step_kind":"assert","description":"The scenario flips to review_state=approved.","user_visible_outcome":"The badge updates and an activity row is recorded."}]'::jsonb),
  ('admin.module-list-loads', 'admin', 'p2', 'Module list loads', 'The /internal/scenarios/modules page lists every catalogued module.', '7df5e0458032e663', '[{"step_kind":"action","action_kind":"navigate","description":"Go to /internal/scenarios/modules."},{"step_kind":"assert","description":"Every module is listed.","user_visible_outcome":"Counts per detail-level are shown for each module."}]'::jsonb),
  ('bibliography.create-block-via-plus', 'bibliography', 'p1', 'Create a bibliography block', 'Add a bibliography block to a document via the +Add menu.', '726f59174f1035c3', '[{"step_kind":"setup","description":"Open a document in the studio."},{"step_kind":"action","action_kind":"click","description":"Click +Add → Bibliography."},{"step_kind":"assert","description":"A bibliography block is appended.","user_visible_outcome":"The block shows the empty-state hint for adding entries."}]'::jsonb),
  ('bibliography.add-entry-by-doi', 'bibliography', 'p0', 'Add entry by DOI', 'Type a DOI into the bibliography block and confirm the entry resolves and renders.', '40b1eb88f95f84fb', '[{"step_kind":"setup","description":"Open a bibliography block."},{"step_kind":"action","action_kind":"type","description":"Enter a DOI (e.g. 10.1038/nphys1170) in the new-entry input."},{"step_kind":"action","action_kind":"click","description":"Click Resolve / submit."},{"step_kind":"assert","description":"The DOI metadata is fetched.","user_visible_outcome":"The entry shows authors, year, title and the resolved cite key."}]'::jsonb),
  ('bibliography.cite-in-paragraph-renders-badge', 'bibliography', 'p1', 'Cite a key in a paragraph', 'Typing @cite{key} in a paragraph renders a citation badge linked to the bibliography entry.', '24cfa8e4c2000639', '[{"step_kind":"setup","description":"Have at least one bibliography entry in the document."},{"step_kind":"action","action_kind":"type","description":"In a paragraph, type @cite{<that key>}."},{"step_kind":"assert","description":"A citation badge appears inline.","user_visible_outcome":"Hovering the badge shows the resolved author / year tooltip."}]'::jsonb),
  ('bibliography.list-renders-all-entries', 'bibliography', 'p1', 'Bibliography block lists every entry', 'When the document has multiple bibliography entries, the bibliography block renders all of them in order.', 'e453ca78c156999c', '[{"step_kind":"setup","description":"Add three bibliography entries."},{"step_kind":"assert","description":"The bibliography block lists all three.","user_visible_outcome":"Each entry shows author, year, title in the document’s cite style."}]'::jsonb),
  ('formulas.open-panel', 'formulas', 'p1', 'Open the formula library panel', 'From the activity bar, open the Formulas panel and confirm the library list loads.', '7ada576bfd4725c3', '[{"step_kind":"setup","description":"Open a document in the flow editor."},{"step_kind":"action","action_kind":"click","description":"Click the Formulas (Σ) icon in the activity bar."},{"step_kind":"assert","description":"The Formulas panel slides out.","user_visible_outcome":"Both My document and Library tabs are present."}]'::jsonb),
  ('formulas.insert-from-library', 'formulas', 'p0', 'Insert a saved formula', 'Pick a formula from the library and confirm it inserts as an equation block at the cursor.', 'de61736ee4bdbd99', '[{"step_kind":"setup","description":"Open the Formulas panel."},{"step_kind":"action","action_kind":"click","description":"Click any formula card in the Library tab."},{"step_kind":"assert","description":"An equation block is inserted at the cursor.","user_visible_outcome":"The block’s LaTeX matches the library entry."}]'::jsonb),
  ('formulas.save-equation-to-library', 'formulas', 'p1', 'Save equation to library', 'Save an existing equation block to the formula library so it appears in My document.', '1d7d95cce216356f', '[{"step_kind":"setup","description":"Have an equation block in the document."},{"step_kind":"action","action_kind":"click","description":"Open the equation block’s kebab menu."},{"step_kind":"action","action_kind":"click","description":"Click Save to library."},{"step_kind":"assert","description":"The formula appears in the My document tab.","user_visible_outcome":"The library entry shows the saved LaTeX."}]'::jsonb),
  ('settings.update-document-title', 'settings', 'p1', 'Rename the document', 'Edit the document title from the settings drawer and confirm the change persists.', 'f004f26b0e98b179', '[{"step_kind":"setup","description":"Open the Document settings drawer."},{"step_kind":"action","action_kind":"type","description":"Edit the title to a new value."},{"step_kind":"action","action_kind":"click","description":"Click outside / save."},{"step_kind":"assert","description":"The header reflects the new title.","user_visible_outcome":"After a reload the new title persists."}]'::jsonb),
  ('settings.toggle-equation-numbering', 'settings', 'p1', 'Toggle equation numbering', 'Toggle the equation-numbering switch in document settings and confirm the preview updates.', '4708b0fb1418ffb8', '[{"step_kind":"setup","description":"Open the Document settings drawer."},{"step_kind":"action","action_kind":"click","description":"Click the Equation numbering toggle."},{"step_kind":"assert","description":"Preview equations show / hide their numbers.","user_visible_outcome":"The state persists across reload."}]'::jsonb),
  ('settings.pick-export-format', 'settings', 'p2', 'Pick a default export format', 'In settings, change the default export format and confirm the export menu reflects it.', '69b8d46016051125', '[{"step_kind":"setup","description":"Open the Document settings drawer."},{"step_kind":"action","action_kind":"click","description":"Open the Default export format selector."},{"step_kind":"action","action_kind":"click","description":"Pick LaTeX (or DOCX / PDF)."},{"step_kind":"assert","description":"The selector shows the new value.","user_visible_outcome":"The Export menu opens to that format by default."}]'::jsonb),
  ('settings.user-preferences-open', 'settings', 'p2', 'Open user preferences', 'Open the user-level Preferences modal from the avatar menu.', 'f1266c8909123f81', '[{"step_kind":"action","action_kind":"click","description":"Click the avatar menu."},{"step_kind":"action","action_kind":"click","description":"Click Preferences."},{"step_kind":"assert","description":"The Preferences modal mounts.","user_visible_outcome":"Theme, locale and editor preferences are listed."}]'::jsonb)
),
ins AS (
  INSERT INTO e2e.scenario (
    id, slug, title, description, module_id, criticality, detail_level,
    review_state, execution_mode, template, automation_content,
    is_deleted, created_at, updated_at, created_by
  )
  SELECT gen_random_uuid(), c.slug, c.title, c.descr, m.id, c.criticality, 'l2',
         'draft', 'integration', 'standard', c.automation_content,
         false, NOW(), NOW(), 'claude-coverage-gaps'
  FROM cat c
  JOIN e2e.module m ON m.slug = c.module_slug
  WHERE NOT EXISTS (SELECT 1 FROM e2e.scenario s WHERE s.slug = c.slug)
  RETURNING id, slug
)
INSERT INTO e2e.scenario_version (
  scenario_id, version_number, detail_level, title, description,
  steps, generation_provenance, generated_by
)
SELECT i.id, 1, 'l2', c.title, c.descr, c.steps, 'llm_draft', 'claude-coverage-gaps'
FROM ins i
JOIN cat c ON c.slug = i.slug;

UPDATE e2e.scenario s
SET current_version_id = v.id, updated_at = NOW()
FROM e2e.scenario_version v
WHERE v.scenario_id = s.id
  AND v.version_number = 1
  AND s.created_by = 'claude-coverage-gaps'
  AND s.current_version_id IS NULL;

DO $$
DECLARE
  n_l1_remaining INT;
  n_new          INT;
BEGIN
  SELECT count(*) INTO n_l1_remaining FROM e2e.scenario WHERE detail_level='l1' AND NOT is_deleted;
  SELECT count(*) INTO n_new FROM e2e.scenario WHERE created_by = 'claude-coverage-gaps' AND NOT is_deleted;
  RAISE NOTICE 'L1 scenarios remaining: %', n_l1_remaining;
  RAISE NOTICE 'new coverage-gap scenarios in catalogue: %', n_new;
END$$;

COMMIT;
